language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: glacial-reaches-21907
  api_key:
    secure: lB+efi4Yn8aXPg7dQzoy15vOroQxpSGUvUnofBw5Jpu6MJBogg5NqfAuXeiuqparxmaLwCT5ukMwHVUiC7LI6Xi2A85XmKLueiA9AQK/nhcqTi6V6gyrQuad+JpAy8Fp9evz7Zm5BJYvUTrLEbYBUna8bjDDgcWCSqesXri26Nf8QeqQouKBOYKS9EitkhwUnUNGPDlVhwje84nEMrgeM/jloHTDEu6qn+YJiXBQ45wSEJ0vsvYMIKprrFo0EpJ+vmTvrPXmhqHFXUNh78pjLjQL+v7glaaldLeFni1yueI3ANh1J2zi4fj2OvORYFdmH3sPjtHKBX9ha5eb95JQo8w+MhACE2VM2/wmJuZ4gFK8iAPDzMYgXO/D3v2rLLuu+XScMM3yuQD1m3l3BjpTTmWn6wnF6k8bzZJ4XXLDTCLj4WH2tkPUstT4TtNr34C5NDB5/hkpoKUqUE5wNWKFtDsUr1ncd+qwG6ZJ7iSIFqR4uTLylhbG+1Tn41sxbuM8ekBpoxRJRgOnvqQ7oqyFcT8MkR5LKqAk7MpeM9UGQyEkhi9A47P/5/lSm0gwcfgxHNZyDQdA6XICEV5nllpVevmLcP3SVA4XTVXN3umXXJgAhK75lJbfFUj5f6nkIoWJ7dJT4VT2J+hxBp3OW++YY7Zqnf1ULSYungrj7Dk+b84=
